package misora;

import misora.commands.Command;
import misora.components.Parser;
import misora.components.Storage;
import misora.components.TaskList;
import misora.components.Ui;
import misora.exceptions.MisoraException;

/**
 * The main entry point of the Misora application.
 * <p>
 * {@code Misora} coordinates the interaction between the {@link Ui},
 * {@link Parser}, {@link TaskList}, and {@link Storage}. It is responsible
 * for initializing the application, handling user input, executing commands,
 * and terminating the program gracefully when the user exits.
 */
public class Misora {

    /**
     * Handles loading tasks from and saving tasks to persistent storage.
     */
    private final Storage storage;

    /**
     * The in-memory list of tasks currently managed by the application.
     */
    private TaskList tasks;

    /**
     * Handles all user interaction, including displaying messages and receiving input.
     */
    private final Ui ui;

    /**
     * Constructs a {@code Misora} instance with the specified file path for task storage.
     * <p>
     * Attempts to load previously saved tasks from the file. If loading fails
     * due to a {@link MisoraException}, an empty {@link TaskList} is created
     * and an error message is displayed to the user.
     *
     * @param filePath the path to the file used for storing tasks
     */
    public Misora(String filePath) {
        assert filePath != null : "File path should not be null";

        ui = new Ui();
        storage = new Storage(filePath);
        try {
            tasks = new TaskList(storage.load());
        } catch (MisoraException e) {
            System.out.println(ui.showLoadingError());
            tasks = new TaskList();
        }

        assert tasks != null : "TaskList should always be initialized";
    }

    /**
     * Processes a single user input string, parses it into a {@link Command},
     * executes the command, and returns the resulting response.
     * <p>
     * Any exceptions thrown during parsing or execution are caught, and
     * the error message is returned instead of crashing the application.
     *
     * @param userInput the raw input string entered by the user
     * @return the response generated by executing the command, or an error message
     */
    public String getResponse(String userInput) {
        assert userInput != null : "User input should not be null";

        try {
            Command c = Parser.parse(userInput);
            return c.execute(tasks, ui, storage);
        } catch (MisoraException e) {
            return e.getMessage();
        }
    }

    /**
     * Returns the welcome message displayed to the user when the application starts.
     *
     * @return the welcome message string
     */
    public String getWelcomeMessage() {
        assertInvariant();
        return ui.showWelcome();
    }

    private void assertInvariant() {
        assert ui != null : "UI must exist";
        assert storage != null : "Storage must exist";
        assert tasks != null : "TaskList must exist";
    }

    /**
     * Returns the exit message displayed to the user when the application terminates.
     *
     * @return the exit message string
     */
    public String getExitMessage() {
        return ui.showExit();
    }
}
